package com.aquavera.aquavera.viewmodel

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel

class LangViewModel : ViewModel() {
    var currentLanguage by mutableStateOf("en")
        private set

    private val translations = mapOf(
        "en" to mapOf(
            "app_name" to "AquaVera",
            "farmer_portal" to "FARMER PORTAL",
            "farmer_registration" to "FARMER REGISTRATION",
            "login" to "Log In",
            "signup" to "Sign Up",
            "email" to "Email Address",
            "password" to "Password",
            "forgot_password" to "Forgot Password?",
            "no_account" to "Don't have an account? ",
            "already_account" to "Already have an account? ",
            "full_name" to "Full Name",
            "email_address" to "Email Address",
            "phone_number" to "Phone Number",
            "confirm_password" to "Confirm Password",
            "create_account" to "Create Account",
            "choose_language" to "Choose Your Language",
            "continue" to "Continue",
            "dashboard" to "Dashboard",
            "requests" to "Requests",
            "users" to "Users",
            "operational_dashboard" to "Operational Dashboard",
            "real_time_overview" to "Real-time overview of irrigation requests",
            "total_requests" to "Total Requests (7D)",
            "pending_approvals" to "Pending Approvals",
            "volume_allocated" to "Volume Allocated (m³)",
            "flagged_anomalies" to "Flagged Anomalies",
            "crop_distribution" to "Crop Distribution",
            "wheat" to "Wheat",
            "sugarcane" to "Sugarcane",
            "rice" to "Rice",
            "cotton" to "Cotton",
            "menu" to "Menu",
            "search" to "Search",
            "profile" to "Profile",
            "logged_in_as" to "Logged in as User",
            "secure_logout" to "Secure Logout",
            "user_management" to "User Management",
            "otp_verification" to "OTP Verification",
            "enter_otp" to "Enter the 6-digit code sent to your email",
            "verify" to "Verify",
            "resend_otp" to "Resend OTP",
            "reset_password" to "Reset Password",
            "enter_email_reset" to "Enter your email to receive a password reset code",
            "send_code" to "Send Code",
            "new_password" to "New Password",
            "save_password" to "Save Password",
            "password_updated" to "Password updated successfully!"
        ),
        "mr" to mapOf(
            "app_name" to "AquaVera",
            "farmer_portal" to "शेतकरी पोर्टल",
            "farmer_registration" to "शेतकरी नोंदणी",
            "login" to "लॉगिन करा",
            "signup" to "साइन अप करा",
            "email" to "ईमेल पत्ता",
            "password" to "पासवर्ड",
            "forgot_password" to "पासवर्ड विसरलात?",
            "no_account" to "तुमचे खाते नाही का? ",
            "already_account" to "आधीच खाते आहे का? ",
            "full_name" to "पूर्ण नाव",
            "email_address" to "ईमेल पत्ता",
            "phone_number" to "फोन नंबर",
            "confirm_password" to "पासवर्डची पुष्टी करा",
            "create_account" to "खाते तयार करा",
            "choose_language" to "तुमची भाषा निवडा",
            "continue" to "पुढे जा",
            "dashboard" to "डॅशबोर्ड",
            "requests" to "विनंत्या",
            "users" to "वापरकर्ते",
            "operational_dashboard" to "कार्यक्षम डॅशबोर्ड",
            "real_time_overview" to "सिंचन विनंत्यांचे रिअल-टाइम विहंगावलोकन",
            "total_requests" to "एकूण विनंत्या (७ दिवस)",
            "pending_approvals" to "प्रलंबित मंजूरी",
            "volume_allocated" to "वाटप केलेले पाण्याचे प्रमाण (m³)",
            "flagged_anomalies" to "चिन्हांकित विसंगती",
            "crop_distribution" to "पीक वितरण",
            "wheat" to "गहू",
            "sugarcane" to "ऊस",
            "rice" to "भात",
            "cotton" to "कापूस",
            "menu" to "मेनू",
            "search" to "शोधा",
            "profile" to "प्रोफाइल",
            "logged_in_as" to "वापरकर्ता म्हणून लॉग इन केले",
            "secure_logout" to "सुरक्षित लॉगआउट",
            "user_management" to "वापरकर्ता व्यवस्थापन",
            "otp_verification" to "OTP पडताळणी",
            "enter_otp" to "तुमच्या ईमेलवर पाठवलेला ६-अंकी कोड प्रविष्ट करा",
            "verify" to "पडताळणी करा",
            "resend_otp" to "OTP पुन्हा पाठवा",
            "reset_password" to "पासवर्ड रिसेट करा",
            "enter_email_reset" to "पासवर्ड रिसेट कोड मिळवण्यासाठी तुमचा ईमेल प्रविष्ट करा",
            "send_code" to "कोड पाठवा",
            "new_password" to "नवीन पासवर्ड",
            "save_password" to "पासवर्ड जतन करा",
            "password_updated" to "पासवर्ड यशस्वीरित्या अपडेट झाला!"
        ),
        "hi" to mapOf(
            "app_name" to "AquaVera",
            "farmer_portal" to "किसान पोर्टल",
            "farmer_registration" to "किसान पंजीकरण",
            "login" to "लॉग इन करें",
            "signup" to "साइन अप करें",
            "email" to "ईमेल पता",
            "password" to "पासवर्ड",
            "forgot_password" to "पासवर्ड भूल गए?",
            "no_account" to "क्या आपका खाता नहीं है? ",
            "already_account" to "पहले से ही खाता है? ",
            "full_name" to "पूरा नाम",
            "email_address" to "ईमेल पता",
            "phone_number" to "फोन नंबर",
            "confirm_password" to "पासवर्ड की पुष्टि करें",
            "create_account" to "खाता बनाएं",
            "choose_language" to "अपनी भाषा चुनें",
            "continue" to "जारी रखें",
            "dashboard" to "डैशबोर्ड",
            "requests" to "अनुरोध",
            "users" to "उपयोगकर्ता",
            "operational_dashboard" to "परिचालन डैशबोर्ड",
            "real_time_overview" to "सिंचाई अनुरोधों का वास्तविक समय अवलोकन",
            "total_requests" to "कुल अनुरोध (7 दिन)",
            "pending_approvals" to "लंबित अनुमोदन",
            "volume_allocated" to "आवंटित मात्रा (m³)",
            "flagged_anomalies" to "चिह्नित विसंगतियां",
            "crop_distribution" to "फसल वितरण",
            "wheat" to "गेहूँ",
            "sugarcane" to "गन्ना",
            "rice" to "चावल",
            "cotton" to "कपास",
            "menu" to "मेनू",
            "search" to "खोजें",
            "profile" to "प्रोफ़ाइल",
            "logged_in_as" to "उपयोगकर्ता के रूप में लॉग इन किया",
            "secure_logout" to "सुरक्षित लॉगआउट",
            "user_management" to "उपयोगकर्ता प्रबंधन",
            "otp_verification" to "OTP सत्यापन",
            "enter_otp" to "अपने ईमेल पर भेजा गया 6-अंकीय कोड दर्ज करें",
            "verify" to "सत्यापित करें",
            "resend_otp" to "OTP पुनः भेजें",
            "reset_password" to "पासवर्ड रिसेट करें",
            "enter_email_reset" to "पासवर्ड रिसेट कोड प्राप्त करने के लिए अपना ईमेल दर्ज करें",
            "send_code" to "कोड भेजें",
            "new_password" to "नया पासवर्ड",
            "save_password" to "पासवर्ड सहेजें",
            "password_updated" to "पासवर्ड सफलतापूर्वक अपडेट किया गया!"
        )
    )

    fun setLanguage(lang: String) {
        currentLanguage = lang
    }

    fun toggleLanguage() {
        currentLanguage = if (currentLanguage == "en") "mr" else "en"
    }

    fun t(key: String): String {
        return translations[currentLanguage]?.get(key) ?: key
    }
}
